#!/bin/bash
# Script to create openpilot validation PR for panda changes

echo "This script will help you create an openpilot PR to validate your panda changes"
echo ""
echo "Steps to create the validation PR:"
echo ""
echo "1. Fork openpilot if you haven't already:"
echo "   Go to https://github.com/commaai/openpilot and click 'Fork'"
echo ""
echo "2. Clone your openpilot fork:"
echo "   git clone https://github.com/MAVRICK-1/openpilot.git"
echo "   cd openpilot"
echo ""
echo "3. Create a new branch:"
echo "   git checkout -b validate-panda-pip-package"
echo ""
echo "4. Update the panda submodule to your branch:"
echo "   cd panda"
echo "   git fetch origin pip-package-setup"
echo "   git checkout pip-package-setup"
echo "   cd .."
echo ""
echo "5. Commit the submodule update:"
echo "   git add panda"
echo "   git commit -m 'Update panda submodule to test pip package setup'"
echo ""
echo "6. Push to your fork:"
echo "   git push origin validate-panda-pip-package"
echo ""
echo "7. Create a PR on GitHub:"
echo "   Go to https://github.com/commaai/openpilot/pulls"
echo "   Click 'New pull request'"
echo "   Select your fork and branch"
echo "   Title: 'Validation PR for panda #2239 - pip package setup'"
echo "   Description: 'This PR validates the changes in commaai/panda#2239'"
echo ""
echo "The openpilot CI will then test your panda changes!"