Import('CC', 'platform')

env = Environment(
  CC=CC,
  CFLAGS=[
    '-nostdlib',
    '-fno-builtin',
    '-std=gnu11',
  ],
  CPPPATH=[".", "../board"],
)

if platform == 'Darwin':
  env.PrependENVPath('PATH', '/opt/homebrew/bin')
env.SharedLibrary("safety/libpandasafety.so", ["safety/test.c"])
env.SharedLibrary("usbprotocol/libpandaprotocol.so", ["usbprotocol/test.c"])
