// ********************* Bare interrupt handlers *********************
// Only implemented the STM32F413 interrupts for now
#pragma once
#include "drivers/interrupts.h"


static inline void WWDG_IRQHandler(void) {handle_interrupt(WWDG_IRQn);}
static inline void PVD_IRQHandler(void) {handle_interrupt(PVD_IRQn);}
static inline void TAMP_STAMP_IRQHandler(void) {handle_interrupt(TAMP_STAMP_IRQn);}
static inline void RTC_WKUP_IRQHandler(void) {handle_interrupt(RTC_WKUP_IRQn);}
static inline void FLASH_IRQHandler(void) {handle_interrupt(FLASH_IRQn);}
static inline void RCC_IRQHandler(void) {handle_interrupt(RCC_IRQn);}
static inline void EXTI0_IRQHandler(void) {handle_interrupt(EXTI0_IRQn);}
static inline void EXTI1_IRQHandler(void) {handle_interrupt(EXTI1_IRQn);}
static inline void EXTI2_IRQHandler(void) {handle_interrupt(EXTI2_IRQn);}
static inline void EXTI3_IRQHandler(void) {handle_interrupt(EXTI3_IRQn);}
static inline void EXTI4_IRQHandler(void) {handle_interrupt(EXTI4_IRQn);}
static inline void DMA1_Stream0_IRQHandler(void) {handle_interrupt(DMA1_Stream0_IRQn);}
static inline void DMA1_Stream1_IRQHandler(void) {handle_interrupt(DMA1_Stream1_IRQn);}
static inline void DMA1_Stream2_IRQHandler(void) {handle_interrupt(DMA1_Stream2_IRQn);}
static inline void DMA1_Stream3_IRQHandler(void) {handle_interrupt(DMA1_Stream3_IRQn);}
static inline void DMA1_Stream4_IRQHandler(void) {handle_interrupt(DMA1_Stream4_IRQn);}
static inline void DMA1_Stream5_IRQHandler(void) {handle_interrupt(DMA1_Stream5_IRQn);}
static inline void DMA1_Stream6_IRQHandler(void) {handle_interrupt(DMA1_Stream6_IRQn);}
static inline void ADC_IRQHandler(void) {handle_interrupt(ADC_IRQn);}
static inline void CAN1_TX_IRQHandler(void) {handle_interrupt(CAN1_TX_IRQn);}
static inline void CAN1_RX0_IRQHandler(void) {handle_interrupt(CAN1_RX0_IRQn);}
static inline void CAN1_RX1_IRQHandler(void) {handle_interrupt(CAN1_RX1_IRQn);}
static inline void CAN1_SCE_IRQHandler(void) {handle_interrupt(CAN1_SCE_IRQn);}
static inline void EXTI9_5_IRQHandler(void) {handle_interrupt(EXTI9_5_IRQn);}
static inline void TIM1_BRK_TIM9_IRQHandler(void) {handle_interrupt(TIM1_BRK_TIM9_IRQn);}
static inline void TIM1_UP_TIM10_IRQHandler(void) {handle_interrupt(TIM1_UP_TIM10_IRQn);}
static inline void TIM1_TRG_COM_TIM11_IRQHandler(void) {handle_interrupt(TIM1_TRG_COM_TIM11_IRQn);}
static inline void TIM1_CC_IRQHandler(void) {handle_interrupt(TIM1_CC_IRQn);}
static inline void TIM2_IRQHandler(void) {handle_interrupt(TIM2_IRQn);}
static inline void TIM3_IRQHandler(void) {handle_interrupt(TIM3_IRQn);}
static inline void TIM4_IRQHandler(void) {handle_interrupt(TIM4_IRQn);}
static inline void I2C1_EV_IRQHandler(void) {handle_interrupt(I2C1_EV_IRQn);}
static inline void I2C1_ER_IRQHandler(void) {handle_interrupt(I2C1_ER_IRQn);}
static inline void I2C2_EV_IRQHandler(void) {handle_interrupt(I2C2_EV_IRQn);}
static inline void I2C2_ER_IRQHandler(void) {handle_interrupt(I2C2_ER_IRQn);}
static inline void SPI1_IRQHandler(void) {handle_interrupt(SPI1_IRQn);}
static inline void SPI2_IRQHandler(void) {handle_interrupt(SPI2_IRQn);}
static inline void USART1_IRQHandler(void) {handle_interrupt(USART1_IRQn);}
static inline void USART2_IRQHandler(void) {handle_interrupt(USART2_IRQn);}
static inline void USART3_IRQHandler(void) {handle_interrupt(USART3_IRQn);}
static inline void EXTI15_10_IRQHandler(void) {handle_interrupt(EXTI15_10_IRQn);}
static inline void RTC_Alarm_IRQHandler(void) {handle_interrupt(RTC_Alarm_IRQn);}
static inline void OTG_FS_WKUP_IRQHandler(void) {handle_interrupt(OTG_FS_WKUP_IRQn);}
static inline void TIM8_BRK_TIM12_IRQHandler(void) {handle_interrupt(TIM8_BRK_TIM12_IRQn);}
static inline void TIM8_UP_TIM13_IRQHandler(void) {handle_interrupt(TIM8_UP_TIM13_IRQn);}
static inline void TIM8_TRG_COM_TIM14_IRQHandler(void) {handle_interrupt(TIM8_TRG_COM_TIM14_IRQn);}
static inline void TIM8_CC_IRQHandler(void) {handle_interrupt(TIM8_CC_IRQn);}
static inline void DMA1_Stream7_IRQHandler(void) {handle_interrupt(DMA1_Stream7_IRQn);}
static inline void FSMC_IRQHandler(void) {handle_interrupt(FSMC_IRQn);}
static inline void SDIO_IRQHandler(void) {handle_interrupt(SDIO_IRQn);}
static inline void TIM5_IRQHandler(void) {handle_interrupt(TIM5_IRQn);}
static inline void SPI3_IRQHandler(void) {handle_interrupt(SPI3_IRQn);}
static inline void UART4_IRQHandler(void) {handle_interrupt(UART4_IRQn);}
static inline void UART5_IRQHandler(void) {handle_interrupt(UART5_IRQn);}
static inline void TIM6_DAC_IRQHandler(void) {handle_interrupt(TIM6_DAC_IRQn);}
static inline void TIM7_IRQHandler(void) {handle_interrupt(TIM7_IRQn);}
static inline void DMA2_Stream0_IRQHandler(void) {handle_interrupt(DMA2_Stream0_IRQn);}
static inline void DMA2_Stream1_IRQHandler(void) {handle_interrupt(DMA2_Stream1_IRQn);}
static inline void DMA2_Stream2_IRQHandler(void) {handle_interrupt(DMA2_Stream2_IRQn);}
static inline void DMA2_Stream3_IRQHandler(void) {handle_interrupt(DMA2_Stream3_IRQn);}
static inline void DMA2_Stream4_IRQHandler(void) {handle_interrupt(DMA2_Stream4_IRQn);}
static inline void CAN2_TX_IRQHandler(void) {handle_interrupt(CAN2_TX_IRQn);}
static inline void CAN2_RX0_IRQHandler(void) {handle_interrupt(CAN2_RX0_IRQn);}
static inline void CAN2_RX1_IRQHandler(void) {handle_interrupt(CAN2_RX1_IRQn);}
static inline void CAN2_SCE_IRQHandler(void) {handle_interrupt(CAN2_SCE_IRQn);}
static inline void OTG_FS_IRQHandler(void) {handle_interrupt(OTG_FS_IRQn);}
static inline void DMA2_Stream5_IRQHandler(void) {handle_interrupt(DMA2_Stream5_IRQn);}
static inline void DMA2_Stream6_IRQHandler(void) {handle_interrupt(DMA2_Stream6_IRQn);}
static inline void DMA2_Stream7_IRQHandler(void) {handle_interrupt(DMA2_Stream7_IRQn);}
static inline void USART6_IRQHandler(void) {handle_interrupt(USART6_IRQn);}
static inline void I2C3_EV_IRQHandler(void) {handle_interrupt(I2C3_EV_IRQn);}
static inline void I2C3_ER_IRQHandler(void) {handle_interrupt(I2C3_ER_IRQn);}
static inline void DFSDM1_FLT0_IRQHandler(void) {handle_interrupt(DFSDM1_FLT0_IRQn);}
static inline void DFSDM1_FLT1_IRQHandler(void) {handle_interrupt(DFSDM1_FLT1_IRQn);}
static inline void CAN3_TX_IRQHandler(void) {handle_interrupt(CAN3_TX_IRQn);}
static inline void CAN3_RX0_IRQHandler(void) {handle_interrupt(CAN3_RX0_IRQn);}
static inline void CAN3_RX1_IRQHandler(void) {handle_interrupt(CAN3_RX1_IRQn);}
static inline void CAN3_SCE_IRQHandler(void) {handle_interrupt(CAN3_SCE_IRQn);}
static inline void RNG_IRQHandler(void) {handle_interrupt(RNG_IRQn);}
static inline void FPU_IRQHandler(void) {handle_interrupt(FPU_IRQn);}
static inline void UART7_IRQHandler(void) {handle_interrupt(UART7_IRQn);}
static inline void UART8_IRQHandler(void) {handle_interrupt(UART8_IRQn);}
static inline void SPI4_IRQHandler(void) {handle_interrupt(SPI4_IRQn);}
static inline void SPI5_IRQHandler(void) {handle_interrupt(SPI5_IRQn);}
static inline void SAI1_IRQHandler(void) {handle_interrupt(SAI1_IRQn);}
static inline void UART9_IRQHandler(void) {handle_interrupt(UART9_IRQn);}
static inline void UART10_IRQHandler(void) {handle_interrupt(UART10_IRQn);}
static inline void QUADSPI_IRQHandler(void) {handle_interrupt(QUADSPI_IRQn);}
static inline void FMPI2C1_EV_IRQHandler(void) {handle_interrupt(FMPI2C1_EV_IRQn);}
static inline void FMPI2C1_ER_IRQHandler(void) {handle_interrupt(FMPI2C1_ER_IRQn);}
static inline void LPTIM1_IRQHandler(void) {handle_interrupt(LPTIM1_IRQn);}
static inline void DFSDM2_FLT0_IRQHandler(void) {handle_interrupt(DFSDM2_FLT0_IRQn);}
static inline void DFSDM2_FLT1_IRQHandler(void) {handle_interrupt(DFSDM2_FLT1_IRQn);}
static inline void DFSDM2_FLT2_IRQHandler(void) {handle_interrupt(DFSDM2_FLT2_IRQn);}
static inline void DFSDM2_FLT3_IRQHandler(void) {handle_interrupt(DFSDM2_FLT3_IRQn);}
