#include "board/config.h"
#include "board/utils.h"
#include "board/drivers/usb.h"

USB_OTG_GlobalTypeDef *USBx = USB_OTG_HS;

void OTG_HS_IRQ_Handler(void) {
  NVIC_DisableIRQ(OTG_HS_IRQn);
  usb_irqhandler();
  NVIC_EnableIRQ(OTG_HS_IRQn);
}

void usb_init(void) {
  REGISTER_INTERRUPT(OTG_HS_IRQn, OTG_HS_IRQ_Handler, 1500000U, FAULT_INTERRUPT_RATE_USB)
  USBx->GAHBCFG &= ~(USB_OTG_GAHBCFG_GINT);
  USBx->GUSBCFG |= USB_OTG_GUSBCFG_PHYSEL;
  USBx->GUSBCFG &= ~(USB_OTG_GUSBCFG_FHMOD | USB_OTG_GUSBCFG_FDMOD);
  USBx->GUSBCFG |= USB_OTG_GUSBCFG_FDMOD;
  delay(250000);
  while ((USBx->GRSTCTL & USB_OTG_GRSTCTL_AHBIDL) == 0U);
  USBx->GRSTCTL |= USB_OTG_GRSTCTL_CSRST;
  while ((USBx->GRSTCTL & USB_OTG_GRSTCTL_CSRST) == USB_OTG_GRSTCTL_CSRST);
  USBx->GCCFG |= USB_OTG_GCCFG_PWRDWN;
  for (uint8_t i = 0U; i < 15U; i++) { USBx->DIEPTXF[i] = 0U; }
  USBx_DEVICE->DCTL |= USB_OTG_DCTL_SDIS;
  USBx->GCCFG &= ~(USB_OTG_GCCFG_VBDEN);
  USBx->GOTGCTL |= USB_OTG_GOTGCTL_BVALOEN;
  USBx->GOTGCTL |= USB_OTG_GOTGCTL_BVALOVAL;
  USBx_PCGCCTL = 0U;
  USBx_DEVICE->DCFG |= DCFG_FRAME_INTERVAL_80;
  USBx_DEVICE->DCFG |= USB_OTG_SPEED_FULL | USB_OTG_DCFG_NZLSOHSK;
  USBx->GRSTCTL = (USB_OTG_GRSTCTL_TXFFLSH | (0x10U << 6));
  while ((USBx->GRSTCTL & USB_OTG_GRSTCTL_TXFFLSH) == USB_OTG_GRSTCTL_TXFFLSH);
  USBx->GRSTCTL = USB_OTG_GRSTCTL_RXFFLSH;
  while ((USBx->GRSTCTL & USB_OTG_GRSTCTL_RXFFLSH) == USB_OTG_GRSTCTL_RXFFLSH);
  USBx_DEVICE->DIEPMSK = 0U;
  USBx_DEVICE->DOEPMSK = 0U;
  USBx_DEVICE->DAINTMSK = 0U;
  USBx_DEVICE->DIEPMSK &= ~(USB_OTG_DIEPMSK_TXFURM);
  USBx->GINTMSK = 0U;
  USBx->GINTSTS = 0xBFFFFFFFU;
  USBx->GINTMSK = USB_OTG_GINTMSK_USBRST | USB_OTG_GINTMSK_ENUMDNEM | USB_OTG_GINTMSK_OTGINT |
                  USB_OTG_GINTMSK_RXFLVLM | USB_OTG_GINTMSK_GONAKEFFM | USB_OTG_GINTMSK_GINAKEFFM |
                  USB_OTG_GINTMSK_OEPINT | USB_OTG_GINTMSK_IEPINT |
                  USB_OTG_GINTMSK_CIDSCHGM | USB_OTG_GINTMSK_SRQIM | USB_OTG_GINTMSK_MMISM;
  USBx->GUSBCFG |= ((USBD_FS_TRDT_VALUE << 10) & USB_OTG_GUSBCFG_TRDT);
  USBx->GAHBCFG |= USB_OTG_GAHBCFG_GINT;
  USBx_DEVICE->DCTL &= ~(USB_OTG_DCTL_SDIS);
  NVIC_EnableIRQ(OTG_HS_IRQn);
}
