# :set noet
PROJ_NAME = panda
CFLAGS  = -g -O0 -Wall

CFLAGS += -mlittle-endian -mthumb -mcpu=cortex-m4
CFLAGS += -mhard-float -DSTM32F4 -DSTM32F413xx
STARTUP_FILE = startup_stm32f413xx

include build.mk

