# :set noet
PROJ_NAME = comma
CFLAGS  = -g -O0 -Wall -std=gnu90

CFLAGS += -mlittle-endian -mthumb -mcpu=cortex-m3
CFLAGS += -msoft-float -DSTM32F2 -DSTM32F205xx
STARTUP_FILE = startup_stm32f205xx

include build.mk
