Import('build_project', 'base_project_f4', 'base_project_h7')

extra = ["-include", "board/drivers/led.c"]
build_project("panda", base_project_f4, extra)
build_project("panda_h7", base_project_h7, extra)
