import opendbc

env = Environment(
  CFLAGS=[
    '-nostdlib',
    '-fno-builtin',
    '-std=gnu11',
    '-Wfatal-errors',
    '-Wno-pointer-to-int-cast',
  ],
  CPPPATH=[".", "../../", "../../board/", opendbc.INCLUDE_PATH],
)

panda = env.SharedObject("panda.os", "panda.c")
main_state = env.SharedObject("main_state.os", "../../board/main_state.c")
can_comms = env.SharedObject("can_comms.os", "../../board/can_comms.c")
libpanda = env.SharedLibrary("libpanda.so", [panda, main_state, can_comms])
