import opendbc

env = Environment(
  CFLAGS=[
    '-nostdlib',
    '-fno-builtin',
    '-std=gnu11',
    '-Wfatal-errors',
    '-Wno-pointer-to-int-cast',
  ],
  CPPPATH=[".", "../../", "../../board/", opendbc.INCLUDE_PATH],
)

sources = [
  "panda.c",
  "../../board/fake_stm.c",
  "../../board/drivers/can_common.c",
  "../../board/can_comms.c",
  "../../board/safety.c",
  "../../board/sys/faults.c",
  "../../board/libc.c",
  "../../board/utils.c",
  "../../board/main_state.c",
  "../../board/boards/boards.c",
]
objects = [env.SharedObject(f"obj/{source.rsplit('/', 1)[-1][:-2]}.os", source) for source in sources]
libpanda = env.SharedLibrary("libpanda.so", objects)
