#!/usr/bin/env python3
import argparse
import textwrap
from pathlib import Path

from opendbc.car.car_helpers import interfaces
from opendbc.car.fingerprints import MIGRATION
from openpilot.tools.lib.logreader import LogReader


DEFAULT_ROUTE = "77611a1fac303767/2020-03-24--09-50-38/3"
DEFAULT_PREFIX_EVENTS = 300


def parser_used_addrs(CI, RI):
  used = set()
  for cp in CI.can_parsers.values():
    used |= {(cp.bus, addr) for addr in cp.addresses}
  if getattr(RI, "rcp", None) is not None:
    used |= {(RI.rcp.bus, addr) for addr in RI.rcp.addresses}
  return used


def load_events_and_used_addrs(lr, CP):
  CI = interfaces[CP.carFingerprint](CP)
  RI = interfaces[CP.carFingerprint].RadarInterface(CP)

  events = []
  for msg in lr:
    if msg.which() != "can":
      continue

    can_msgs = [(int(can.address), bytes(can.dat), int(can.src)) for can in msg.can if int(can.src) <= 2]
    event = (msg.logMonoTime, can_msgs)
    events.append(event)
    CI.update([event])
    RI.update([event])

  return events, parser_used_addrs(CI, RI)


def build_payload(route, prefix_events):
  lr = LogReader(route)
  CP = lr.first("carParams").as_builder()
  CP.carFingerprint = str(MIGRATION.get(CP.carFingerprint, CP.carFingerprint))
  events, used = load_events_and_used_addrs(lr, CP)

  counts = bytearray()
  records = bytearray()
  dictionary = []
  dictionary_idxs = {}
  msg_count = 0
  max_count = 0

  for event_idx, (_, event) in enumerate(events):
    can_msgs = []
    for address, dat, bus in event:
      if (event_idx >= prefix_events) and ((bus, address) not in used):
        continue
      assert address < 0x800, f"extended address not supported: {address:#x}"
      assert len(dat) <= 8, f"CAN-FD data not supported: {len(dat)}"
      can_msgs.append((address, dat, bus))

    assert len(can_msgs) <= 255
    counts.append(len(can_msgs))
    max_count = max(max_count, len(can_msgs))
    msg_count += len(can_msgs)

    for address, dat, bus in can_msgs:
      key = (address, bus, len(dat))
      if key not in dictionary_idxs:
        assert len(dictionary) < 256
        dictionary_idxs[key] = len(dictionary)
        dictionary.append(key)

      records.append(dictionary_idxs[key])
      records += dat

  payload = bytes(counts + records)
  return payload, len(counts), msg_count, max_count, CP.carFingerprint, dictionary


def format_u16_array(vals):
  lines = []
  for i in range(0, len(vals), 12):
    chunk = vals[i:i + 12]
    lines.append("  " + ", ".join(f"0x{v:04x}U" for v in chunk) + ",")
  return "\n".join(lines)


def format_u8_array(vals):
  lines = []
  for i in range(0, len(vals), 16):
    chunk = vals[i:i + 16]
    lines.append("  " + ", ".join(f"0x{v:02x}U" for v in chunk) + ",")
  return "\n".join(lines)


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("--route", default=DEFAULT_ROUTE)
  parser.add_argument("--prefix-events", type=int, default=DEFAULT_PREFIX_EVENTS)
  parser.add_argument("--output", type=Path, default=Path(__file__).with_name("can_replay_data.h"))
  parser.add_argument("--bin-output", type=Path, default=Path(__file__).with_name("can_replay_data.bin"))
  args = parser.parse_args()

  payload, event_count, msg_count, max_count, fingerprint, dictionary = build_payload(args.route, args.prefix_events)
  dict_addrs = [address for address, _, _ in dictionary]
  dict_bus_lens = [(bus << 4) | length for _, bus, length in dictionary]

  header = f"""\
// Generated by {Path(__file__).name}; do not edit by hand.
// Route: {args.route}
// Car fingerprint: {fingerprint}
// First {args.prefix_events} CAN events include all bus <= 2 traffic; later events keep parser-used traffic.

#pragma once

#define CAN_REPLAY_EVENT_COUNT {event_count}U
#define CAN_REPLAY_MSG_COUNT {msg_count}U
#define CAN_REPLAY_DATA_SIZE {len(payload)}U
#define CAN_REPLAY_MAX_MSGS_PER_EVENT {max_count}U
#define CAN_REPLAY_DICT_COUNT {len(dictionary)}U

static const uint16_t can_replay_dict_addr[CAN_REPLAY_DICT_COUNT] = {{
{format_u16_array(dict_addrs)}
}};

static const uint8_t can_replay_dict_bus_len[CAN_REPLAY_DICT_COUNT] = {{
{format_u8_array(dict_bus_lens)}
}};

extern const uint8_t can_replay_data[CAN_REPLAY_DATA_SIZE];
__asm__(
  ".section .rodata.can_replay_data,\\"a\\",%progbits\\n"
  ".balign 4\\n"
  ".global can_replay_data\\n"
  ".type can_replay_data, %object\\n"
  "can_replay_data:\\n"
  ".incbin \\"board/debug/can_replay_data.bin\\"\\n"
  ".size can_replay_data, {len(payload)}\\n"
  ".balign 4\\n"
  ".previous\\n"
);
"""
  args.bin_output.write_bytes(payload)
  args.output.write_text(header)
  print(textwrap.dedent(f"""\
    wrote {args.output}
    wrote {args.bin_output}
    route: {args.route}
    fingerprint: {fingerprint}
    events: {event_count}
    messages: {msg_count}
    max messages/event: {max_count}
    dictionary entries: {len(dictionary)}
    payload bytes: {len(payload)}
  """).strip())


if __name__ == "__main__":
  main()
