import os

Import('build_project', 'base_project_h7')

flags = [
  "-DPANDA_JUNGLE",
]
if os.getenv("FINAL_PROVISIONING"):
  flags += ["-DFINAL_PROVISIONING"]

build_project("panda_jungle_h7", base_project_h7, flags + ["-include", "board/drivers/led.c"])
