name: repo

on:
  schedule:
    - cron: "0 15 1 * *"
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    name: pre-commit autoupdate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./setup.sh
    - name: pre-commit autoupdate
      run: |
        source .venv/bin/activate
        git config --global --add safe.directory '*'
        pre-commit autoupdate
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@f689536846d983d7c4f399cd9b789c38c963aaca
      with:
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: Update pre-commit hook versions
        title: 'pre-commit: autoupdate hooks'
        branch: pre-commit-updates
        base: master
        delete-branch: true
